app = "ci-auto-rescue"
primary_region = "sjc"

[build]
  dockerfile = "github-app/Dockerfile"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0


