name: Guard Tags

on:
  create:
    tags:
      - "*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag naming
        run: |
          TAG="${{ github.ref_name }}"

          # Skip validation for demo/* tags
          if [[ "$TAG" =~ ^demo/ ]]; then
            echo "✅ Demo tag: $TAG (validation skipped)"
            exit 0
          fi

          # Enforce strict semantic versioning for release tags
          # Allow: v1.2.3, v1.2.3-alpha.1, v1.2.3-beta.2, v1.2.3-rc.3
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-((alpha|beta|rc)\.[0-9]+))?$ ]]; then
            echo "❌ Invalid tag format: $TAG"
            echo ""
            echo "Valid formats:"
            echo "  - v1.2.3 (stable release)"
            echo "  - v1.2.3-alpha.1 (alpha pre-release)"
            echo "  - v1.2.3-beta.2 (beta pre-release)"
            echo "  - v1.2.3-rc.3 (release candidate)"
            echo "  - demo/* (demo snapshots)"
            exit 1
          fi

          echo "✅ Valid release tag: $TAG"
