name: Nova CI-Rescue Auto-Fix

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR to run Nova on"
        required: true
  # optional: allow manual via UI too; keep any other triggers you want
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  run-nova:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Nova
        run: pip install nova-ci-rescue

      - name: Run Nova
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          NOVA_DEFAULT_LLM_MODEL: ${{ secrets.NOVA_DEFAULT_LLM_MODEL }}
        run: |
          echo "Running on PR #${{ inputs.pr_number }}"
          nova fix . --max-iters 2 --timeout 300
